### ISSUE TITLE
Does blackbox_initialize need to be run on an svn repo?

### ISSUE THREAD

**Issue by oberoc** [StackExchange/blackbox#148]
In the README.md overview, it says "Getting started is easy. Just cd into a Git, Mercurial, Subversion or Perforce repository and run blackbox_initialize." but under commands: blackbox_initialize "Enable blackbox for a GIT or HG `repo". I have had to make a bunch of changes in blackbox_initialize to make it work for svn (if that is the case). Thanks.

**Comment by TomOnTime** [comment]
Hi Tino!

The code isn't very well tested on SubVersion.  I'd love to merge your changes into the code.

**Comment by jvanasco** [comment]
I tried to get this to work on subversion with no luck.

It looks like the issue is this line (https://github.com/StackExchange/blackbox/blob/master/bin/blackbox_initialize#L25)

    vcs_ignore keyrings/live/pubring.gpg~ keyrings/live/pubring.kbx~ keyrings/live/secring.gpg

which calls this line https://github.com/StackExchange/blackbox/blob/master/bin/_blackbox_common.sh#L568-L571

```
# Subversion
function vcs_ignore_svn() {
  svn propset svn:ignore "$(vcs_relative_path "$file")"
}
```

that would generate this command for `./foo.txt`

    svn propset svn:ignore . foo.txt

but the correct command is:

    svn propset svn:ignore foo.txt .

**Comment by jvanasco** [comment]
_blackbox_common.sh needs this edit:

```
function vcs_ignore_svn() {
  svn propset svn:ignore "$file" "$(vcs_relative_path)"
}
```

blackbox_initialize.sh needs this edit:

```
if is_in_svn; then
	echo "subversion automatically tracks ignores"
else
	IGNOREFILE="$(vcs_ignore_file_path)"
	test -f "$IGNOREFILE" && vcs_add "$IGNOREFILE"

	# Make a suggestion:
	echo
	echo
	echo 'NEXT STEP: You need to manually check these in:'
	echo '     ' $VCS_TYPE commit -m\'INITIALIZE BLACKBOX\' keyrings "$IGNOREFILE"
fi
```

**Comment by jvanasco** [comment]
I issued a PR with some updates for SVN here https://github.com/StackExchange/blackbox/pull/150

**Comment by klauern** [comment]
Is this still an issue?  I am evaluating some tools on our repositories, and we're unfortunately stuck on SVN for the time being.

**Comment by tlimoncelli** [comment]
As far as I know the PR solved the major issues. There may be some minor issues, but I don't use SVN any more so I do not know what they are.  It is certainly worth giving a try.

**Comment by jvanasco** [comment]
@klauern subversion support largely works right now .  The flow/messages could be better on the file changes/commits.  I was working on a PR that disabled "svn commit", and just did "svn add", but never finished it.  This is rather insignificant though, because .001% of acts are adding a file, .1% are editing and 99.9% is decrypting.

**Comment by klauern** [comment]
That's great to hear.  I wish I were on Git, but it's hard to move a mountain sometimes...
