### ISSUE TITLE
gpg: skipped packet of type 12 in keybox

### ISSUE THREAD

**Issue by rowhit** [StackExchange/blackbox#222]
I am unable to get blackbox_postdeploy to work properly. It does not decrypt files as expected. I receive following error:
========== Importing keychain: START
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox

However, when I try to decrypt a file using gpg directly it works fine. Below is the output of gpg --version
gpg (GnuPG) 2.2.1
libgcrypt 1.8.1

**Comment by tlimoncelli** [comment]
I haven't seen that error before. When I do a web search for it, I get links like this https://bbs.archlinux.org/viewtopic.php?id=227089 which might be related.

On the off chance that the problem is in  your .config file, could you make sure your manual gpg command is the same one used by the scripts?  In particular, make sure you are using `--homedir=` to point to the keychains in your repo. Otherwise it will use the ones in `$HOME` which have different contents.

**Comment by rowhit** [comment]
Yes. The gpg command is the same. The gpg-agent also using the the --homedir:
gpg-agent --homedir $HOME/.config/$PROJ/keyrings/live --use-standard-socket --daemon

When I wish to decrypt the file manually using gpg, it works fine. But not with blackbox_postdeploy.

**Comment by tlimoncelli** [comment]
Interesting. I wonder what is different between the two.  Some ideas that come to mind: Perhaps an env variable?  The PATH (is this a different gpg binary?)   Are certain files having the problem but not others? (with so little output it is difficult to tell if some files work and others don't)

Sadly I'm not a super gpg expert.

**Comment by rowhit** [comment]
I should have looked into the script earlier. Its actually all bash scripts. I just had to disable line that setup the PATH in the beginning of blackbox_postdeploy file. Everything works fine thereon. Thanks for prompt response.
