### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by gjabell** [StackExchange/blackbox#302]
I am packaging blackbox for Alpine Linux and there hasn't been a new release in over a year. Does anyone know when the next release will be, or could someone create one so we don't have to follow git?

Thanks!

**Comment by tlimoncelli** [comment]
Hi!

This last year has been very chaotic for me.  I haven’t had time to put
much effort into BB.  Where this most affects the project seems to be
portability outside of CentOS.  I apologize, especially to people on
Windows and macOS who seem to be most affected.

This project started out as a few simple scripts that just called GPG with
the right flags so that I didn't have to remember long command lines. I
created them not because I'm a GPG expert, but I know so little: Once I
guess my way through GPG's ludicrous number of flags and options I want to
record what I've learned in the scripts.  Sadly, now most of the support
questions I get are actually GPG questions, which I have little or no idea
how to support.

The system grew without much planning.  Therefore the code is brittle and
difficult to modify.  The code needs significant refactoring and a better
test subsystem.  The golang branch has some excellent ideas and is going in
the right direction.

I'm not sure where this message is going.  If you'd like to volunteer to
help out, please let me know. (no contribution too small, or to big!)

Thanks,
Tom

**Comment by gjabell** [comment]
Hey, totally understand and you for all the hard work you've put into it :)

I'll keep this project in mind if I have some extra time for contributions!

**Comment by tlimoncelli** [comment]
I hope to do a release by the end of this week... or next week if the tests need fixing.

**Comment by tlimoncelli** [comment]
New release completed.

**Comment by gjabell** [comment]
Thank you!
